### PR TITLE
OCCM: add sec group logic for octavia

### LINKED ISSUE #1830: octavia-ingress-controller / occm : Different Octavia behavior from Ingress vs svctype LoadBalancer
/kind bug

**What happened**:

When I deploy an ingress object into the cluster, I get a loadbalancer in Openstack that has an attached Floating ip and security Group.  When I change the type of a service from NodePort to LoadBalancer, a load balancer is created with an attached Floating ip but no security group is created.

Is this expected behavoir?

I'm trying to deploy kubeflow but it uses Istio and Istio uses Gateway and VirtualService in preference to Ingress.

As a result I cannot access Kubeflow dashboards.

**What you expected to happen**:

I expected that changing the type of a Service from NodePort to LoadBalancer would result in a working Octavia LoadBalancer to include FIP, and Security Groups.

Said security groups get created when the loadbalancer is initiated by an Ingress deployed to the cluster.

**How to reproduce it**:

Deploy Kubeflow.  Change the istio-ingressgateway service type from NodePort to LoadBalancer.

Also tried [cloud-provider-openstack](https://github.com/kubernetes/cloud-provider-openstack)/[docs](https://github.com/kubernetes/cloud-provider-openstack/tree/master/docs)/[openstack-cloud-controller-manager](https://github.com/kubernetes/cloud-provider-openstack/tree/master/docs/openstack-cloud-controller-manager)/expose-applications-using-loadbalancer-type-service.md

and this failed as well

**Anything else we need to know?**:

**Environment**:

Octavia Ingress Controller:
docker.io/k8scloudprovider/octavia-ingress-controller:latest"

```
App                   Version   Status  Scale  Charm                 Channel   Rev  Exposed  Message
containerd            go1.13.8  active      6  containerd            stable    200  no       Container runtime available
easyrsa               3.0.1     active      1  easyrsa               stable    441  no       Certificate Authority connected.
etcd                  3.4.5     active      3  etcd                  stable    655  no       Healthy with 3 known peers
flannel               0.11.0    active      6  flannel               stable    619  no       Flannel subnet 10.1.15.1/24
grafana                         active      1  grafana               stable     51  yes      Ready
kubernetes-master     1.21.11   active      2  kubernetes-master     stable   1106  no       Kubernetes master running.
kubernetes-worker     1.21.11   active      4  kubernetes-worker     stable    838  yes      Kubernetes worker running.
openstack-integrator  xena      active      1  openstack-integrator  stable    204  no       Ready
prometheus                      active      1  prometheus2           stable     25  no       Ready
telegraf                        active      6  telegraf              stable     44  no       Monitoring kubernetes-worker/2 (source version/commit 26e531a)
```

### PR DESCRIPTION
**Pull request by jichenjc**
**What this PR does / why we need it**:

**Which issue this PR fixes(if applicable)**:
fixes #1830 

**Special notes for reviewers**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/openstack/loadbalancer.go [hunk 1]
```diff
@@ -2757,6 +2764,13 @@ func (lbaas *LbaasV2) updateOctaviaLoadBalancer(ctx context.Context, clusterName
 		}
 	}
 
+	if lbaas.opts.ManageSecurityGroups {
+		err := lbaas.updateSecurityGroup(clusterName, service, nodes)
```
Comment (chrigl) [inline pkg/openstack/loadbalancer.go:2768]: Do we need a separate `updateSecurityGroup`? The name above `ensureSecurityGroup` suggests to handle both?

**Comment by jichenjc** [comment]
/approve

got lgtm already, wait for long time already
