### PR TITLE
Optimize route reconciliation logic

### LINKED ISSUE #2089: [oocm] generates an excessive number of os-interface api requests
> /kind bug

**What happened**:
We recently noticed that our nova api is handling a constant excessive amount of os-interface (list) calls.
This in turn puts a lot of strain on our neutron API as os-interface calls gets forwarded by nova to neutron as get_ports API calls.

It turns out this constant high load is almost exclusively caused by various occm instances running in our OpenStack installation.

Looking at the occm code there is [five different places](https://github.com/kubernetes/cloud-provider-openstack/search?q=getAttachedInterfacesByID) where `getAttachedInterfacesByID` is called: for routes, load balancers and instances.

It seems the use of `getAttachedInterfacesByID` for the routes controller is the most costly inducing a lot of os_interfaces calls at a high frequency:
[For every instance in the project `os_interfaces` is called at the rate of the routes controller](https://github.com/kubernetes/cloud-provider-openstack/blob/98b9a89ceb0379e794e6ada1976e32c9da80af31/pkg/openstack/routes.go#L65-L66) which is 10 seconds by default. This is regardless of the cluster size. We have a cluster with 4 nodes in a project with 1000 instances and in this case occm is generating about 1000 os_interface list calls every 10 seconds.

I would like to start discussing options how the current behaviour  could be improved, so that the base load of generated API requests by occm is reduced for bigger setups.

My first suggestion would be:
Instead of discovering node ip addresses in three different control loops independently (load balancers, routes, instances) they should only be fetched from the instance controller that reconciles the node status. All other control loops should only read ip addresses from the node status (k8s API).

**What you expected to happen**:
That occm generates less constant load on the OpenStack APIs

**How to reproduce it**:
Create a cluster in a project with a lots of vms and configure oocm to set cloud-routes.

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: 1.25

### PR DESCRIPTION
**Pull request by kayrus**
**What this PR does / why we need it**:

the `openstack.Routes`' `ListRoutes` method must not loop over all project servers just to resolve a couple of route's next hops to node names. This PR resolves the node name only when it's found in the route's next hop using cached k8s API calls for nodes listing.

**Which issue this PR fixes(if applicable)**:
fixes #2089 

**Special notes for reviewers**:

**Release note**:

```release-note
Improve performance of the `ListRoutes` method, especially when an OpenStack project contains hundreds of non-k8s nodes
```

### CODE REVIEW

**Comment by jichenjc** [comment]
still fixing gate, we can continue the code review before that..

**Comment by zetaab** [comment]
/override openstack-cloud-csi-manila-e2e-test

manila is broken currently

**Comment by kayrus** [comment]
Manila e2e tests are broken. What is the process for the PR review?

**Comment by jichenjc** [comment]
/override openstack-cloud-csi-manila-e2e-test

that's something we need fix later, for now, let's ignore this

**Comment by kayrus** [comment]
@jichenjc could you please review this PR? Or do I need to wait for assigned reviewers approval?

**Comment by jichenjc** [comment]
no, I will read this along with other reviewers, will do soon, thanks for the reminder

**Comment by kayrus** [comment]
@anguslees @FengyunPan2 @zetaab @jichenjc kindly ping

File: pkg/openstack/routes.go [hunk 1]
```diff
@@ -180,22 +211,29 @@ func updateAllowedAddressPairs(network *gophercloud.ServiceClient, port *neutron
 
 // CreateRoute creates the described managed route
 func (r *Routes) CreateRoute(ctx context.Context, clusterName string, nameHint string, route *cloudprovider.Route) error {
-	klog.V(4).Infof("CreateRoute(%v, %v, %v)", clusterName, nameHint, route)
-
-	onFailure := newCaller()
+	r.Lock()
```
Comment (jichenjc) [inline pkg/openstack/routes.go:214]: do we have any criteria for this lock? 
e.g what the resource action should be lock/unlock? e.g all POST/UPDATE operation?

File: pkg/openstack/openstack.go [hunk 2]
```diff
@@ -461,3 +459,11 @@ func (os *OpenStack) Routes() (cloudprovider.Routes, bool) {
 	klog.V(1).Info("Claiming to support Routes")
 	return r, true
 }
+
+// SetInformers implements InformerUser interface by setting up informer-fed caches to
+// leverage Kubernetes API for caching
+func (os *OpenStack) SetInformers(informerFactory informers.SharedInformerFactory) {
```
[the remark this answers is not in the document]
Comment (kayrus) [reply pkg/openstack/openstack.go:465]: this is needed for https://github.com/kubernetes/cloud-provider/blob/11e49706691b05e67ac6ca4acae4a2607a739352/cloud.go#L71-L74 interface

[the remark this answers is not in the document]
Comment (jichenjc) [reply pkg/openstack/openstack.go:465]: ok, will read more about the inform logic in cloud provider , that's something not pay attention before , thanks for the link

**Comment by jichenjc** [comment]
/lgtm

ok, might need more time to consume the code logic for informer and lock but let's get this merge to test
maybe @zetaab can help review as well

**Comment by kayrus** [comment]
@zetaab kindly ping

File: pkg/openstack/routes.go (hunk 1 above)
Comment (kayrus) [reply pkg/openstack/routes.go:214]: @jichenjc gophercloud now supports atomic routes update. I submitted a new draft PR to use this feature: https://github.com/kubernetes/cloud-provider-openstack/pull/2134
It's based on this PR. Are there any updates on when this PR can be merged?

**Comment by kayrus** [comment]
@jichenjc @zetaab I had to rebase

**Comment by kayrus** [comment]
@jichenjc @zetaab kindly ping

**Comment by kayrus** [comment]
cc @lingxiankong @anguslees @FengyunPan2

File: pkg/openstack/routes.go [hunk 3]
```diff
@@ -35,97 +36,127 @@ import (
...
+	pages, err := ports.List(network, opts).AllPages()
+	if mc.ObserveRequest(err) != nil {
+		return nil, err
+	}
+	ports, err := ports.ExtractPorts(pages)
+	if err != nil {
+		return nil, err
+	}
+
+	var networkIDs []string
```
Comment (zetaab) [inline pkg/openstack/routes.go:117]: this does not contain unique values for networkid?

File: pkg/openstack/routes.go [hunk 4]
```diff
@@ -35,97 +36,127 @@ import (
...
+			TargetNode:      nodeName, //contains the nexthop address if node name was not found
 			Blackhole:       !foundNode,
 			DestinationCIDR: item.DestinationCIDR,
 		}
 		routes = append(routes, &route)
 	}
 
+	// detect router's private network ID for further VM ports filtering
+	r.Lock()
+	r.networkIDs, err = getRouterNetworkIDs(r.network, r.os.routeOpts.RouterID)
```
Comment (zetaab) [inline pkg/openstack/routes.go:94]: is this really changing so often that we need to fetch this all the time? In general networks are not changing quite often? (spoiler: I am not using this feature at all)

**Review by zetaab — COMMENTED** [review]
some comments, but like mentioned - I do not use this feature so I have not 100% understanding what is even needed

File: pkg/openstack/routes.go (hunk 3 above)
Comment (kayrus) [reply pkg/openstack/routes.go:117]: duplicate values are less probable, since router cannot handle the same network more than once.

File: pkg/openstack/routes.go (hunk 4 above)
Comment (kayrus) [reply pkg/openstack/routes.go:94]: There is a low probability that this may happen. Nevertheless, I decided to be on the safe side, since it's just one API call.

**Comment by kayrus** [comment]
>  I do not use this feature so I have not 100% understanding what is even needed

hm. IMHO this is used in every openstack based k8s cluster, and the `router-id` is a required config option.

**Comment by zetaab** [comment]
its not? example from kops https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/cloudup/openstack/cloud.go#L835-L892

**Comment by kayrus** [comment]
I was confused by https://github.com/kubernetes/cloud-provider-openstack/blob/31f475117755f5dcf55f89ab2f340b55c8ae32cb/pkg/openstack/openstack.go#L132 and https://github.com/kubernetes/cloud-provider-openstack/blob/31f475117755f5dcf55f89ab2f340b55c8ae32cb/pkg/openstack/routes.go#L49 comment. 

And apologies, I've never used kops.

**Comment by zetaab** [comment]
Interesting, why that is required? I have used cloud provider openstack for 7 years without that. 

```
I0302 21:25:15.943948       1 openstack.go:439] openstack.Routes() called
W0302 21:25:16.355725       1 openstack.go:466] Error initialising Routes support: router-id not set in cloud provider config
```

but everything works like should?

**Comment by kayrus** [comment]
> but everything works like should?

in my test environment the amount of API calls has been decreased by an order of magnitude, if not by two.

Could you please skip `openstack-cloud-csi-manila-e2e-test`?

**Comment by zetaab** [comment]
/override openstack-cloud-csi-manila-e2e-test

yeah but I mean, the interesting question is that why that is marked as required if its not really needed.

**Comment by kayrus** [comment]
> yeah but I mean, the interesting question is that why that is marked as required if its not really needed.

I'll cover this in my next PR: #2134

**Comment by kayrus** [comment]
@zetaab @jichenjc what is the process for backporting this fix to earlier releases?

**Comment by jichenjc** [comment]
just cherry pick ,but we ususally backport a bug instead of a feature ..

**Comment by kayrus** [comment]
@jichenjc well, our API endpoints are overloaded by useless API requests, which cause nasty performance issues and sometimes outages. Let me try to cherry-pick and let's see how will it go.

File: pkg/openstack/routes.go [hunk 5]
```diff
@@ -35,97 +36,127 @@ import (
...
+			for _, v := range node.Status.Addresses {
+				if v.Type == v1.NodeInternalIP {
+					ip := net.ParseIP(v.Address)
+					if ip == nil {
+						continue
+					}
+					if needIPv6 && ip.To4() == nil {
+						return v.Address
+					}
+					return v.Address
```
Comment (majewsky) [inline pkg/openstack/routes.go:152]: This if-branch is ineffective because the return value is the same regardless of whether the condition is true.

Comment (kayrus) [reply pkg/openstack/routes.go:152]: Thanks, good catch!
Fixed in atomic routes PRs.
