### PR TITLE
Fix GetMaxVolLimit to return correct value

### LINKED ISSUE #633: [Cinder CSI] GetMaxVolLimit returns always max value.
**What happened**:
The function GetMaxVolLimit will always return max value when nodeserver calls it. 

This happens because nodeserver never calls function CreateOpenStackProvider what would imitialize cfg global variable. 

**What you expected to happen**:
GetMaxVolLimit should return the value defined in configuration.

**How to reproduce it (as minimally and precisely as possible)**:
Set cloud-clonfig value "node-volume-attach-limit" to 1-255 and it will be 256.

**Anything else we need to know?**:

Easiest fix would be just add check to the GetMaxVolLimit function if global variable cfg is initialized. 

For example something like this:
```
func GetMaxVolLimit() int64 {
  var err error
  if cfg.Global.AuthUrl == "" {
    cfg, _, err = GetConfigFromFile(configFile)
    if err != nil {
      klog.Errorf("Couldn't load config file!")
    }
  }
  if cfg.BlockStorage.NodeVolumeAttachLimit > 0 && cfg.BlockStorage.NodeVolumeAttachLimit <= 256 {
    return cfg.BlockStorage.NodeVolumeAttachLimit
  }
  return maxVol
}
```
Variable `cfg.Global.AuthUrl` is used to check initialization status as you can not have functional CSI it that value have not been initialized. 

**Environment**:
Cinder CSI master

/kind bug

### PR DESCRIPTION
**Pull request by ramineni**
Values of BlockStorageOpts set in config file are not getting
reflected as of now. This PR is to fix the same

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #633

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

File: pkg/csi/cinder/openstack/openstack_volumes.go [hunk 1]
```diff
@@ -250,6 +250,16 @@ func (os *OpenStack) GetAttachmentDiskPath(instanceID, volumeID string) (string,
 	return "", fmt.Errorf("volume %s has no ServerId", volumeID)
 }
 
+//GetMaxVolLimit returns max vol limit
+func (os *OpenStack) GetMaxVolLimit() int64 {
+	if os.bsOpts.NodeVolumeAttachLimit > 0 && os.bsOpts.NodeVolumeAttachLimit <= 256 {
+		return os.bsOpts.NodeVolumeAttachLimit
+	}
+
+	return maxVol
```
Comment (jichenjc) [inline pkg/csi/cinder/openstack/openstack_volumes.go]: since you are changing this, can we rename this param? maxVol to maxNodeVolumeAttach or simiar?

File: pkg/csi/cinder/openstack/openstack.go [hunk 2]
```diff
@@ -81,16 +83,17 @@ type Config struct {
...
+	klog.Infof("Username: %s", cfg.Global.Username)
+	klog.Infof("UserId: %s", cfg.Global.UserId)
+	klog.Infof("TenantId: %s", cfg.Global.TenantId)
+	klog.Infof("TenantName: %s", cfg.Global.TenantName)
+	klog.Infof("DomainName: %s", cfg.Global.DomainName)
+	klog.Infof("DomainId: %s", cfg.Global.DomainId)
+	klog.Infof("TrustID: %s", cfg.Global.TrustID)
+	klog.Infof("Region: %s", cfg.Global.Region)
+	klog.Infof("CAFile: %s", cfg.Global.CAFile)
+	klog.Infof("Block storage opts: %v", cfg.BlockStorage)
```
Comment (jichenjc) [inline pkg/csi/cinder/openstack/openstack.go]: do we need any doc update for this block storage opts?

Comment (ramineni) [reply pkg/csi/cinder/openstack/openstack.go]: Its already there

File: pkg/csi/cinder/openstack/openstack_volumes.go (hunk 1 above)
Comment (ramineni) [reply pkg/csi/cinder/openstack/openstack_volumes.go]: sure, will update it.

**Comment by adisky** [comment]
Thanks for the fix!!
/approve

**Comment by jichenjc** [comment]
/lgtm 
thanks
