### PR TITLE
[cinder-csi-plugin] ephemeral volume removal

### LINKED ISSUE #2599: [csi-cinder-plugin] Ephemeral Volume removal process
/kind feature

**What happened**:

CSI Ephemeral Volume has been deprecated  #1493 and it requires OpenStack credentials on each node, adding unnecessary complexity to our support processes.

Can we start to removal process of it?

ref #2551

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

### PR DESCRIPTION
**Pull request by sergelogvinov**
Disable creating new deprecated ephemeral volumes

**What this PR does / why we need it**:

Remove deprecated ephemeral volumes.

**Which issue this PR fixes(if applicable)**:
fixes #2599

**Special notes for reviewers**:

Hi, @dulek i've disabled only ephemeral volume creation stage.
What do you think, we should remove all code or make it in two steps (releases)?

Thanks.

**Release note**:

```release-note
In-line ephemeral is no longer available.
```

### CODE REVIEW

**Comment by jichenjc** [comment]
thanks for the PR, could you please update 
- doc needed
- release notes about this PR

**Comment by jichenjc** [comment]
@sergelogvinov from the error seems more clean up needed, maybe sainty test cases?

**Comment by sergelogvinov** [comment]
@jichenjc All tests passed. thanks.

File: pkg/csi/cinder/nodeserver.go [hunk 1]
```diff
@@ -67,22 +66,14 @@ func (ns *nodeServer) NodePublishVolume(ctx context.Context, req *csi.NodePublis
...
 	if len(source) == 0 {
 		return nil, status.Error(codes.InvalidArgument, "NodePublishVolume Staging Target Path must be provided")
 	}
-	_, err := ns.Cloud.GetVolume(volumeID)
-	if err != nil {
-		if cpoerrors.IsNotFound(err) {
-			return nil, status.Error(codes.NotFound, "Volume not found")
-		}
-		return nil, status.Errorf(codes.Internal, "GetVolume failed with error %v", err)
-	}
```
Comment (dulek) [inline pkg/csi/cinder/nodeserver.go:85]: Why do you remove this? This doesn't exactly feel like it's related, with `"csi.storage.k8s.io/ephemeral" == "true"` this code won't be exected.

File: pkg/csi/cinder/nodeserver.go [hunk 2]
```diff
@@ -439,16 +330,7 @@ func (ns *nodeServer) NodeUnstageVolume(ctx context.Context, req *csi.NodeUnstag
...
 	}
 
-	_, err := ns.Cloud.GetVolume(volumeID)
-	if err != nil {
-		if cpoerrors.IsNotFound(err) {
-			klog.V(4).Infof("NodeUnstageVolume: Unable to find volume: %v", err)
-			return nil, status.Error(codes.NotFound, "Volume not found")
-		}
-		return nil, status.Errorf(codes.Internal, "GetVolume failed with error %v", err)
-	}
```
Comment (dulek) [inline pkg/csi/cinder/nodeserver.go:449]: Same here, I think.

File: pkg/csi/cinder/nodeserver.go (hunk 1 above)
Comment (sergelogvinov) [reply pkg/csi/cinder/nodeserver.go:85]: Hi, the main idea is - to remove openstack credentials dependency  from node csi daemonset.

We do not need to check the existence of the Volume in the daemonset by openstack api. When the CSI sidecar calls the NodeStageVolume/NodePublishVolume function, the Volume is already attached to the VM. We just need to find the block device in the /dev/* directory. If any issues occur, the block device mounter will return an error.

I believe, this check `_, err := ns.Cloud.GetVolume(volumeID)` is not necessary here.

What do you think?

Comment (dulek) [reply pkg/csi/cinder/nodeserver.go:85]: It's been a while ago when this check got in in https://github.com/kubernetes/cloud-provider-openstack/pull/676. @jichenjc, do you remember why it was necessary?

@kayrus, what do you think about this?

Comment (jichenjc) [reply pkg/csi/cinder/nodeserver.go:85]: seems last update is commit cc73e20cfe8233ff8ad3dbd040866f164225f6f8
but didn't find the commit message realted 

I am guessing this might prevent some concurrent deletion during the actions here ..

**Comment by jichenjc** [comment]
if no objection, let's merge this soon

**Comment by sergelogvinov** [comment]
i've rebased the PR... Thanks.

**Comment by sergelogvinov** [comment]
All tests passed, can you take a look please @zetaab @mdbooth 
Thanks.

**Review by zetaab — APPROVED** [review]
/approve
/lgtm
