### PR TITLE
[occm] Support re-use load balancer between Services

### LINKED ISSUE #933: [occm] Allow ip address sharing for services of type loadbalancers
> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**The binaries affected**:

- [x] openstack-cloud-controller-manager
- [ ] cinder-csi-plugin
- [ ] k8s-keystone-auth
- [ ] client-keystone-auth
- [ ] octavia-ingress-controller
- [ ] manila-csi-plugin
- [ ] manila-provisioner
- [ ] magnum-auto-healer
- [ ] barbican-kms-plugin

**What happened**:

* Created two services of `type: loadBalancer` having set the same `svc.spec.loadBalancerIP`
* No listener, pool, healthmonitor or members are created for the second service:
  * kubectl describe svc shows:
    `Warning  SyncLoadBalancerFailed  2m32s (x6 over 5m9s)   service-controller  Error syncing load balancer: failed to ensure load balancer: floating IP X.X.X.X is not available`

**What you expected to happen**:

* Controller will add a new listener, pool, healthmonitor and members for the additional port/nodeport to the existing loadbalancer having floating IP X.X.X.X

**How to reproduce it**:

```
$ cat service.yaml 
apiVersion: v1
kind: Service
metadata:
  name: kuard-1
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.200.5
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: kuard
$ cat service2.yaml 
apiVersion: v1
kind: Service
metadata:
  name: kuard-2
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.200.5
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kuard
$ kubectl apply -f service.yaml -f service2.yaml
```

**Anything else we need to know?**:

* Metall LB implements this feature: [docs](https://metallb.universe.tf/usage/#ip-address-sharing)
* We could implement it similar to Metall LB and toggle it via an annotation on services analog to `metallb.universe.tf/allow-shared-ip`

What get's touched by implementing it:
* The creation and reconcile of a loadbalancer by the service name may not work.
  * The above exampe creates the following loadbalancers:
    ```
    +--------------------------------------+-----------------------------------------+-------------+---------------------+------------+
    | id                                   | name                                    | vip_address | provisioning_status | provider   |
    +--------------------------------------+-----------------------------------------+-------------+---------------------+------------+
    | cd117dcf-518e-4a34-8613-d2ba29b3f9e2 | kube_service_kubernetes_default_kuard-1 | 10.6.0.32   | ACTIVE              | vmwareedge |
    | df2281b6-6c0b-46a2-bfbd-6566b5697372 | kube_service_kubernetes_default_kuard-2 | 10.6.0.10   | ACTIVE              | vmwareedge |
    ```
    We would need to adjust the following code to have a common name for mutliple services for the loadBalancer, or detect the loadBalancer by other loadBalancer metadata: https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go#L520
  
  We could enforce the need to set a loadBalancerIP when the `ip-address-sharing` annotation is set and resolve the name for the loadBalancer by using the loadBalancerIP by using for example something like `kube_service_x-x-x-x` for the loadBalancer name

* We would need some additional validation for e.g.:
  * do not allow multiple use of the external port
  * potential other invalid options when merging multiple services of type loadBalancer (e.g. annotations)

There may be other things I didn't consider here.

**Environment**:
- openstack-cloud-controller-manager version: master
- OpenStack version: Queens
- Others: Kubernetes v1.16

### PR DESCRIPTION
**Pull request by lingxiankong**
**What this PR does / why we need it**:
By default, different Services of LoadBalancer type should have
different corresponding cloud load balancers, however,
openstack-cloud-controller-manager allows multiple Services to share a
single load balancer if the Octavia service supports the tag feature
(since version 2.5).

Added a new annotation `loadbalancer.openstack.org/load-balancer-id`
that can be specified for creating Services.

Added a new config option `[LoadBalancer] max-shared-lb` to limit the
number of Services that share a load balancer.

Check the doc for more details.

**Which issue this PR fixes(if applicable)**:
fixes #933

**Special notes for reviewers**:
You can use the image `docker.io/lingxiankong/openstack-cloud-controller-manager-amd64:test` for testing.

**Release note**:

```release-note
[openstack-cloud-controller-manager] Support to share a cloud load balancer between different Services. The load balancer can be either created by other Services or outside the Kubernetes cluster. As the load balancer doesn't relate to a dedicated Service anymore, any scripts relying on that relationship previously need to change to use the load balancer tags instead. Action required.
```

### CODE REVIEW

**Comment by ramineni** [comment]
@lingxiankong This job seems to fail . Could you check
pull-cloud-provider-openstack-check — Job failed.

**Comment by lingxiankong** [comment]
Oh, yes, I paid more attention to `openstack-cloud-controller-manager-e2e-test`, will fix.

**Comment by lingxiankong** [comment]
I've removed the usage of import-boss, I didn't find there is any other repo using it except k/k, so I'd suggest to remove it to avoid too much overhead.

**Comment by ramineni** [comment]
> I've removed the usage of import-boss, I didn't find there is any other repo using it except k/k, so I'd suggest to remove it to avoid too much overhead.

@lingxiankong import-boss works if we have .import-restrictions in place , it prohibits to import some of the k/k packages which are not meant to be used by external repo. Is it failed because of added dependency or any other failure?

**Comment by lingxiankong** [comment]
> @lingxiankong import-boss works if we have .import-restrictions in place , it prohibits to import some of the k/k packages which are not meant to be used by external repo. Is it failed because of added dependency or any other failure?

@ramineni Yeah, it failed once before, there was a new module needed to add to the `.import-restrictions` file, which made me feel unconfortable to maintain such a file that is only used by kubernetes code repo. I was suggesting removing that first because we don't have a policy describing what packages should be allowed and what shouldn't, the second reason is, given there are no other cloud providers using that, why we should spend extra effort maintaining that?

**Comment by ramineni** [comment]
> > @lingxiankong import-boss works if we have .import-restrictions in place , it prohibits to import some of the k/k packages which are not meant to be used by external repo. Is it failed because of added dependency or any other failure?
> 
> @ramineni Yeah, it failed once before, there was a new module needed to add to the `.import-restrictions` file, which made me feel unconfortable to maintain such a file that is only used by kubernetes code repo. I was suggesting removing that first because we don't have a policy describing what packages should be allowed and what shouldn't, the second reason is, given there are no other cloud providers using that, why we should spend extra effort maintaining that?

@lingxiankong Ya, agree its a overhead , ok to be removed I suppose. But we should keep a lookout in general not to use k/k repo packages if alternate external packages/libs available, else its fine.

File: pkg/openstack/loadbalancer.go [hunk 1]
```diff
@@ -3150,45 +3125,64 @@ func (lbaas *LbaasV2) ensureLoadBalancerDeleted(ctx context.Context, clusterName
...
+	// For neutron-lbaas
+	if !lbaas.opts.UseOctavia {
+		return lbaas.ensureLoadBalancerDeletedLegacy(loadbalancer)
+	}
 
-		err = waitLoadbalancerDeleted(lbaas.lb, loadbalancer.ID)
-		if err != nil {
-			return fmt.Errorf("failed to wait for deleted loadbalancer %s: %v", loadbalancer.ID, err)
+	if needDeleteLB && lbaas.opts.CascadeDelete {
+		klog.InfoS("Deleting load balancer", "lbID", loadbalancer.ID, "service", klog.KObj(service))
```
Comment (ramineni) [inline pkg/openstack/loadbalancer.go:3153]: @lingxiankong everywhere Im seeing, you kept 2 logs L 3153, L 3157  logged by default (not debug logs). Is it required ? We can add Deleted confirmation logs to default and other as debug logs?

File: pkg/util/openstack/loadbalancer.go [hunk 2]
```diff
@@ -43,9 +44,10 @@ const (
 	OctaviaFeatureTimeout           = 3
 	OctaviaFeatureAvailabilityZones = 4
 
-	loadbalancerActiveInitDelay = 1 * time.Second
-	loadbalancerActiveFactor    = 1.2
-	loadbalancerActiveSteps     = 19
+	waitLoadbalancerInitDelay   = 5 * time.Second
+	waitLoadbalancerFactor      = 1
+	waitLoadbalancerActiveSteps = 36
```
Comment (ramineni) [inline pkg/util/openstack/loadbalancer.go:49]: this has been increases significantly. any reason?

File: pkg/util/openstack/loadbalancer.go [hunk 3]
```diff
@@ -168,9 +172,39 @@ func waitLoadbalancerActive(client *gophercloud.ServiceClient, loadbalancerID st
 
 	})
 
+	if err == wait.ErrWaitTimeout {
+		err = fmt.Errorf("timeout waiting for the loadbalancer %s", activeStatus)
```
Comment (ramineni) [inline pkg/util/openstack/loadbalancer.go:176]: good to loadbalancer ID here?

File: pkg/util/openstack/loadbalancer.go [hunk 4]
```diff
@@ -196,16 +230,72 @@ func GetLoadbalancerByName(client *gophercloud.ServiceClient, name string) (*loa
...
+	}
+
+	mc := metrics.NewMetricContext("loadbalancer", "update")
+	_, err := loadbalancers.Update(client, lbID, updateOpts).Extract()
+	if mc.ObserveRequest(err) != nil {
+		return err
+	}
+
+	if err := WaitLoadbalancerActive(client, lbID); err != nil {
+		return fmt.Errorf("failed to wait for load balancer ACTIVE after updating: %v", err)
```
Comment (ramineni) [inline pkg/util/openstack/loadbalancer.go:246]: we can add ID here as well?

File: pkg/util/openstack/loadbalancer.go [hunk 5]
```diff
@@ -231,13 +321,32 @@ func CreateListener(client *gophercloud.ServiceClient, lbID string, opts listene
...
+		if cpoerrors.IsNotFound(err) {
+			klog.V(2).Infof("Listener %s for load balancer %s was already deleted: %v", listenerID, lbID, err)
+		} else {
+			_ = mc.ObserveRequest(err)
+			return fmt.Errorf("error deleting listener %s for load balancer %s: %v", listenerID, lbID, err)
+		}
+	}
+
+	if err := WaitLoadbalancerActive(client, lbID); err != nil {
+		return fmt.Errorf("failed to wait for load balancer ACTIVE after deleting listener: %v", err)
```
Comment (ramineni) [inline pkg/util/openstack/loadbalancer.go:344]: can add lbID here

**Comment by ramineni** [comment]
@lingxiankong Can we add functional test as well for this functionality? or is this already tested as part of CI?

File: pkg/openstack/loadbalancer.go (hunk 1 above)
Comment (lingxiankong) [reply pkg/openstack/loadbalancer.go:3153]: Yeah, I did that on purpose. First, the default log level for klog is V(2), we don't need to explicitly use `klog.V(2)`. Second, log the starting and ending point of operations is considered the best practice (at least in openstack) in production and is useful for troubleshooting purpose, e.g. an operation is stuck, without the starting point logging, it's hard to know what the system is doing at that moment.

File: pkg/util/openstack/loadbalancer.go (hunk 2 above)
Comment (lingxiankong) [reply pkg/util/openstack/loadbalancer.go:49]: The comment for the previous code is incorrect, we were not using exponential backoff actually, we were using the fixed interval backoff mechanism, so `loadbalancerActiveFactor    = 1.75` doesn't make any sense. I changed this to: Start with 5s delay, sleep 5s (5*1) between each iteration, try 36 times in max, so the total duration is around 5*36=180s, that should be covering most prod and testing environments.

File: pkg/util/openstack/loadbalancer.go (hunk 3 above)
Comment (lingxiankong) [reply pkg/util/openstack/loadbalancer.go:176]: Agree, will add.

File: pkg/util/openstack/loadbalancer.go (hunk 4 above)
Comment (lingxiankong) [reply pkg/util/openstack/loadbalancer.go:246]: Sure

**Comment by lingxiankong** [comment]
> @lingxiankong Can we add functional test as well for this functionality? or is this already tested as part of CI?

Yes, please see the change in tests/e2e/cloudprovider/test-lb-service.sh

File: pkg/util/openstack/loadbalancer.go (hunk 2 above)
Comment (ramineni) [reply pkg/util/openstack/loadbalancer.go:49]: > we were not using exponential backoff actually, we were using the fixed interval backoff mechanism,

@lingxiankong Didnt get that, I see we are using "wait.ExponentialBackoff" at L158 , https://pkg.go.dev/k8s.io/apimachinery/pkg/util/wait#ExponentialBackoff , as per my understanding it says it is using longer delays between each retry . Isnt it? Are you suggesting the function is not doing as expected?

**Comment by ramineni** [comment]
> > @lingxiankong Can we add functional test as well for this functionality? or is this already tested as part of CI?
> 
> Yes, please see the change in tests/e2e/cloudprovider/test-lb-service.sh

Got it . Thanks. I might have missed it as diff is minimized

File: pkg/util/openstack/loadbalancer.go (hunk 2 above)
Comment (lingxiankong) [reply pkg/util/openstack/loadbalancer.go:49]: If you take a look at the implementation of `ExponentialBackoff`, especially `time.Sleep(backoff.Step())`, see how the sleep time is calculated.

**Comment by ramineni** [comment]
code looks fine to me.Thanks
/lgtm

File: docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md [hunk 6]
```diff
@@ -450,3 +459,110 @@ To enable PROXY protocol support, the openstack-cloud-controller-manager config
...
+Now, create another Service `service-2` but re-use the load balancer created for `service-1` by specifying the annotation `loadbalancer.openstack.org/load-balancer-id`:
+
+```yaml
+kind: Service
+apiVersion: v1
+metadata:
+  name: service-2
+  namespace: default
+  annotations:
+    loadbalancer.openstack.org/load-balancer-id: "2b224530-9414-4302-8163-5abebdcdc84f"
```
Comment (jichenjc) [inline docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md:519]: just curious, if the ID is given but the LB not found or in some race condition like
is deleting, what will happen?

File: docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md [hunk 7]
```diff
@@ -193,6 +194,14 @@ Request Body:
 
   Not supported when `lb-provider=ovn` is configured in openstack-cloud-controller-manager.
 
+- `loadbalancer.openstack.org/load-balancer-id`
+
+  This annotation is automatically added to the Service if it's not specified when creating. After the Service is created successfully it shouldn't be changed, otherwise the Service won't behave as expected.  
+
+  If this annotation is specified with a valid cloud load balancer ID when creating Service, the Service is reusing this load balancer rather than creating another one. Again, it shouldn't be changed after the Service is created.
+
+  If this annotation is specified, the other annotations which define the load balancer features will be ignored.
```
Comment (jichenjc) [inline docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md:203]: I think we should error out on such case, not ignore it ..

**Comment by jichenjc** [comment]
mostly good enough

just some suggestions/questions inline

File: docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md (hunk 6 above)
Comment (lingxiankong) [reply docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md:519]: If the load balancer is not found or in deleting status, service creation will fail.

File: docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md (hunk 7 above)
Comment (lingxiankong) [reply docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md:203]: We can't, with this PR, all the services (either existing or new) will have this annotation created automatically, in controller code it's hard to tell if the request is creating new service or updating an existing one.

**Comment by lingxiankong** [comment]
The job is failing because the devstack has some issues being fixed in the openstack community right now.

File: docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md (hunk 7 above)
Comment (jichenjc) [reply docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md:203]: sorry then I am confused.. if we will create this annottation anyway
and you are saying `If this annotation is specified, the other annotations which define the load balancer features will be ignored` , does this mean we will ignore the other annotation in any case? 

anyway, this is not a blocker so we can wait for CI ready then merge and help me in understand the logic, thanks

Comment (lingxiankong) [reply docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md:203]: As demonstrated in the doc, if you are creating a new service without this annotation, the workflow is the same as previous, but in the end occm adds this annotation to the service. So next time when you updating this service, occm can directly look for the load balancer by ID rather than searching by name.

However, if you create a service with a valid lb id specified, that means you are just creating listener/pool/members in an existing load balancer, which means you can't config something like fixed/floating IP for the lb, the flavor and az, etc.

Comment (jichenjc) [reply docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md:203]: ok, I understand, maybe my thought is overkill ,so , let it be, thanks for the detailed info~

**Comment by lingxiankong** [comment]
The job passed.

**Comment by lingxiankong** [comment]
/override openlab/cloud-provider-openstack-acceptance-test-csi-manila
/override openlab/cloud-provider-openstack-acceptance-test-e2e-conformance
/override openlab/cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.19
/override openlab/cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.20
/override openlab/cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.21
/override openlab/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization
/override openlab/cloud-provider-openstack-e2e-test-csi-cinder
/override openlab/cloud-provider-openstack-multinode-csi-migration-test

**Comment by wouterh-dev** [comment]
Is there a reason that max-shared-lb was set to only 2 by default?
