### PR TITLE
[cinder-csi-plugin] Add metadata search order

### LINKED ISSUE #859: Cinder CSI: wrong instanceID detection in OS with python based cloudinit
/kind bug

**What happened**:

Cinder CSI plugin detects invalid node ID:

```
I1202 13:49:57.542000       1 utils.go:79] GRPC call: /csi.v1.Identity/GetPluginInfo
I1202 13:49:57.542031       1 utils.go:80] GRPC request:
I1202 13:49:57.542113       1 identityserver.go:33] Using default GetPluginInfo
I1202 13:49:57.542119       1 utils.go:85] GRPC response: name:"cinder.csi.openstack.org" vendor_version:"1.1.0"
I1202 13:49:59.023895       1 utils.go:79] GRPC call: /csi.v1.Node/NodeGetInfo
I1202 13:49:59.023927       1 utils.go:80] GRPC request:
I1202 13:49:59.024432       1 mount.go:246] Got instance id from /var/lib/cloud/data/instance-id: i-0008fe64
I1202 13:49:59.298012       1 utils.go:85] GRPC response: node_id:"i-0008fe64" max_volumes_per_node:256 accessible_topology:<segments:<key:"topology.cinder.csi.openstack.org/zone" value:"region-3a" > >
```

OpenStack metadata service supports EC2 metadata API (e.g. `http://169.254.169.254/2009-04-04/meta-data/instance-id`), where nova [generates](https://github.com/openstack/nova/blob/56eac06561bc843dcf7497e8b7ac3027f62544c1/nova/api/metadata/base.py#L255) EC2 id, which doesn't have anything in common with a real OpenStack instance uuid. This EC2 id is used by python cloud-init and saved into the `/var/lib/cloud/data/instance-id`.

Legacy CCM code had an ability to define the [metadata order](https://github.com/kubernetes/cloud-provider-openstack/blob/f8ad69f78a71f945eef6c0858afecbe68f14c79d/docs/provider-configuration.md#metadata-optional-parameters), nevertheless it didn't use the `/var/lib/cloud/data/instance-id` file, but cloudinit drive, which is not really used in modern OpenStack deployments, therefore it always fell back to the [OpenStack metadata service](https://github.com/kubernetes/cloud-provider-openstack/blob/f8ad69f78a71f945eef6c0858afecbe68f14c79d/pkg/util/metadata/metadata.go#L42).

Cinder CSI doesn't have the order option and it [always reads](https://github.com/kubernetes/cloud-provider-openstack/blob/f8ad69f78a71f945eef6c0858afecbe68f14c79d/pkg/csi/cinder/nodeserver.go#L543) the `/var/lib/cloud/data/instance-id` file first, therefore it detects wrong instance ID.

This issue doesn't occur in CoreOS, because CoreOS [cloudinit](https://github.com/coreos/coreos-cloudinit) doesn't write the `/var/lib/cloud/data/instance-id` file.

**What you expected to happen**:

* instance ID code should be cleaned up. Probably it's worth removing the current [CSI code](https://github.com/kubernetes/cloud-provider-openstack/blob/f8ad69f78a71f945eef6c0858afecbe68f14c79d/pkg/csi/cinder/mount/mount.go#L240) and reuse the [CCM configdrive code](https://github.com/kubernetes/cloud-provider-openstack/blob/f8ad69f78a71f945eef6c0858afecbe68f14c79d/pkg/util/metadata/metadata.go#L104)
* add a `search-order` option to the Cinder CSI driver

**How to reproduce it (as minimally and precisely as possible)**:

I was able to reproduce it on a VM, which uses python based [cloudinit](https://cloudinit.readthedocs.io/en/latest/topics/dir_layout.html), e.g. CentOS, Ubuntu, SLES, etc.

**Anything else we need to know?**:

Probably this issue is somehow connected to the #856

So far I'm using the following hotfix:

```diff
diff --git a/pkg/csi/cinder/nodeserver.go b/pkg/csi/cinder/nodeserver.go
index 73ce3f3..3b7646c 100644
--- a/pkg/csi/cinder/nodeserver.go
+++ b/pkg/csi/cinder/nodeserver.go
@@ -539,17 +539,19 @@ func getAvailabilityZoneMetadataService(m openstack.IMetadata) (string, error) {
 }
 
 func getNodeID(mount mount.IMount, metadata openstack.IMetadata) (string, error) {
-       // First try to get instance id from mount provider
-       nodeID, err := getNodeIDMountProvider(mount)
+       // First try to get instance id from metadata service
+       klog.V(3).Infof("Trying to GetInstanceID from metadata service")
+       nodeID, err := getNodeIDMetdataService(metadata)
        if err == nil {
                return nodeID, nil
        }
+       klog.V(3).Infof("Failed to GetInstanceID from metadata service: %v", err)
 
-       klog.V(3).Infof("Trying to GetInstanceID from metadata service")
-       nodeID, err = getNodeIDMetdataService(metadata)
+       nodeID, err = getNodeIDMountProvider(mount)
        if err != nil {
-               klog.V(3).Infof("Failed to GetInstanceID from metadata service: %v", err)
+               klog.V(3).Infof("Failed to GetInstanceID from mount provider: %v", err)
                return "", err
        }
+
        return nodeID, nil
 }
```

**Environment**:
- openstack-cloud-controller-manager version: 1.16
- OS (e.g. from /etc/os-release): CentOS, Ubuntu, SLES

### PR DESCRIPTION
**Pull request by jichenjc**
**The binaries affected**:

IMPORTANT: Please also add the binary name in the title, e.g.
`[openstack-cloud-controller-manager]: Add UDP protocol support`
unless the PR affects multiple binaries.

- [ ] openstack-cloud-controller-manager
- [x] cinder-csi-plugin
- [ ] k8s-keystone-auth
- [ ] client-keystone-auth
- [ ] octavia-ingress-controller
- [ ] manila-csi-plugin
- [ ] manila-provisioner
- [ ] magnum-auto-healer
- [ ] barbican-kms-plugin

**What this PR does / why we need it**:

**Which issue this PR fixes**:
fixes #859 

**Special notes for reviewers**:

**Release note**:

```release-note
for CSI cinder, the search-order defined in cloud.conf is honored , so you can
provide a string like `configDrive,metadataService` or `metadataService,configDrive` to
define the order to get meta from. 
```

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/cloud-provider-openstack/920)

### CODE REVIEW

**Comment by jichenjc** [comment]
@ramineni  @adisky can you help to provide some guide on this 
openlab/cloud-provider-openstack-e2e-test-csi-cinder  failed but I didn't know how to debug and what's wrong ..

File: pkg/csi/cinder/nodeserver.go [hunk 1]
```diff
@@ -545,17 +547,33 @@ func getAvailabilityZoneMetadataService(m openstack.IMetadata) (string, error) {
 	return zone, nil
 }
 
-func getNodeID(mount mount.IMount, metadata openstack.IMetadata) (string, error) {
+func getNodeID(mount mount.IMount, iMetadata openstack.IMetadata, order string) (string, error) {
 	// First try to get instance id from mount provider
-	nodeID, err := getNodeIDMountProvider(mount)
-	if err == nil {
-		return nodeID, nil
+	if len(order) == 0 {
```
Comment (ramineni) [inline pkg/csi/cinder/nodeserver.go]: It would be good if we could set the default order somewhere where config is initialized , so that it could be reused.

**Comment by ramineni** [comment]
please add the release note as well , Support for 'search-order' Metadata opts added in cinder csi and also please update the same in docs as well

**Comment by bzhaoopenstack** [comment]
recheck

**Comment by bzhaoopenstack** [comment]
recheck

**Comment by ramineni** [comment]
> recheck

Its retest in this repo :)

**Comment by bzhaoopenstack** [comment]
@ramineni Thanks. ;-)

**Comment by ramineni** [comment]
Thanks.
/lgtm

File: pkg/csi/cinder/openstack/openstack.go [hunk 2]
```diff
@@ -74,6 +83,7 @@ type BlockStorageOpts struct {
 type Config struct {
 	openstack_provider.Config
 	BlockStorage BlockStorageOpts
+	Metadata     MetadataOpts
```
Comment (lingxiankong) [inline pkg/csi/cinder/openstack/openstack.go]: This option is already included in `openstack_provider.Config`.

File: docs/using-cinder-csi-plugin.md [hunk 3]
```diff
@@ -41,6 +41,13 @@ Encode your ```$CLOUD_CONFIG``` file content using base64.
 Update ```cloud.conf``` configuration in ```manifests/cinder-csi-plugin/csi-secret-cinderplugin.yaml``` file
 by using the result of the above command.
 
+> NOTE: openstack supports get metadata data for new deployed vm through both config drive and metadata service methods. If you need modify the search order, please add Metadata section in your cloud.conf which is openstack cloud definition. For example, below sample makes CSI pod first search metadata service then use config drive. If you don't provide the value, then default search order `configDrive, metadataService` will be used.
+
+```
+[Metadata]
+search-order = metadataService,configDrive
```
[the remark this answers is not in the document]
Comment (jichenjc) [reply docs/using-cinder-csi-plugin.md]: ok

File: pkg/csi/cinder/openstack/openstack.go (hunk 2 above)
Comment (ramineni) [reply pkg/csi/cinder/openstack/openstack.go]: @lingxiankong But metadata opts in cloudprovider config includes additional options as well which is not yet supported by csi cinder, so isnt it better to override?
https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/cloudprovider/providers/openstack/openstack.go#L164

Comment (jichenjc) [reply pkg/csi/cinder/openstack/openstack.go]: maybe later on when we do the refactory, we can consolidate then?

**Comment by jichenjc** [comment]
not related failure ..

2020-02-11 04:04:40.306994 | ubuntu-xenial-citynetwork | --- FAIL: TestRoutes (17.21s)
2020-02-11 04:04:40.307139 | ubuntu-xenial-citynetwork |     openstack_routes_test.go:77: 10.164.2.0/24 via ubuntu-bionic-citynetwork-openlab-0000117831
2020-02-11 04:04:40.307225 | ubuntu-xenial-citynetwork |     openstack_routes_test.go:82: DeleteRoute error: failed to find object

File: pkg/csi/cinder/openstack/openstack.go (hunk 2 above)
Comment (lingxiankong) [reply pkg/csi/cinder/openstack/openstack.go]: > @lingxiankong But metadata opts in cloudprovider config includes additional options as well which is not yet supported by csi cinder, so isnt it better to override?

If ignoring the extra options doesn't break cinder-csi, that would be ok. The config options for those services should be well documented.

Comment (lingxiankong) [reply pkg/csi/cinder/openstack/openstack.go]: > maybe later on when we do the refactory, we can consolidate then?

But if we add `Metadata` option here instead of re-using https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/cloudprovider/providers/openstack/openstack.go#L181, it will be hard for us to refactor in the future because we will introduce incompatible config change.

Comment (jichenjc) [reply pkg/csi/cinder/openstack/openstack.go]: I tested the configuration ,with existing code add cloud.conf by adding [metadata] section
and works fine, I guess we didn't introduce incompatible config change?

my env is down now ,but I am sure it's something like

```
[Global]
username=user
password=pass
auth-url=https://<keystone_ip>/identity/v3
tenant-id=c869168a828847f39f7f06edd7305637
domain-id=2a73b8f597c04551a0fdc8e95544be8a

[metadata]
searchOrder = configDrive,metadata
```

File: docs/using-cinder-csi-plugin.md [hunk 4]
```diff
@@ -41,6 +41,13 @@ Encode your ```$CLOUD_CONFIG``` file content using base64.
 Update ```cloud.conf``` configuration in ```manifests/cinder-csi-plugin/csi-secret-cinderplugin.yaml``` file
 by using the result of the above command.
 
+> NOTE: openstack supports get metadata data for new deployed vm through both config drive and metadata service methods. If you need modify the search order, please add Metadata section in your cloud.conf which is openstack cloud definition. For example, below sample makes CSI pod first search metadata service then use config drive. If you don't provide the value, then default search order `configDrive, metadataService` will be used.
```
Comment (lingxiankong) [inline docs/using-cinder-csi-plugin.md]: My suggestion:

```
> NOTE: In OpenStack, the compute instance uses either config drive or metadata service to retrieve instance-specific data. As the cluster administrator, you are able to config the order in the cloud config file for cinder-csi-plugin, the default configuration is as follows:
```

File: pkg/csi/cinder/openstack/openstack.go (hunk 2 above)
Comment (lingxiankong) [reply pkg/csi/cinder/openstack/openstack.go]: What I mean is, is `Metadata` already defined in `openstack_provider.Config`, isn't it?

File: docs/using-cinder-csi-plugin.md (hunk 4 above)
Comment (jichenjc) [reply docs/using-cinder-csi-plugin.md]: ok

**Comment by ramineni** [comment]
Strange , Im not able to comment in code , so adding here.
@lingxiankong I believe it should ignore extra options, ya proper documentation should avoid confusion on what all supported options. Even though, I think it wont be incompatible change as we are using the same group and parameter name, reusing would be better option as less hassle when we refactor.
@jichenjc I suppose what @lingxiankong meant is remove the line here https://github.com/kubernetes/cloud-provider-openstack/pull/920/files#diff-252011069a949a55c80b81de97af21f9R86 , as Metadata is already defined as part of openstack_provider.Config, so we could reuse the same instead of redefining the struct again.

**Comment by lingxiankong** [comment]
> @lingxiankong I believe it should ignore extra options, ya proper documentation should avoid confusion on what all supported options. Even though, I think it wont be incompatible change as we are using the same group and parameter name, reusing would be better option as less hassle when we refactor.

If most of us prefer to add `Metadata` field explicitly, I am fine with that. @jichenjc could you please update the doc then I think the PR is good to go.

**Comment by jichenjc** [comment]
um... I give another thought and seems the reuse of the param is a better option per suggested by @lingxiankong , I will update the PR..

File: docs/using-cinder-csi-plugin.md (hunk 4 above)
Comment (lingxiankong) [reply docs/using-cinder-csi-plugin.md]: I didn't see the description is changed.

File: pkg/csi/cinder/nodeserver.go [hunk 5]
```diff
@@ -545,17 +547,28 @@ func getAvailabilityZoneMetadataService(m openstack.IMetadata) (string, error) {
...
+		if err == nil {
+			break
+		}
 	}
 
-	klog.V(3).Infof("Trying to GetInstanceID from metadata service")
-	nodeID, err = getNodeIDMetdataService(metadata)
 	if err != nil {
-		klog.V(3).Infof("Failed to GetInstanceID from metadata service: %v", err)
+		klog.V(3).Infof("Failed to GetInstanceID from config drive or metadata service: %v", err)
```
Comment (lingxiankong) [inline pkg/csi/cinder/nodeserver.go]: For error message, can you use `klog.Errorf()`?

File: docs/using-cinder-csi-plugin.md (hunk 4 above)
Comment (lingxiankong) [reply docs/using-cinder-csi-plugin.md]: I didn't see the description is changed as suggested.

File: pkg/csi/cinder/openstack/openstack.go [hunk 6]
```diff
@@ -27,6 +28,7 @@ import (
 	"github.com/spf13/pflag"
 	gcfg "gopkg.in/gcfg.v1"
 	openstack_provider "k8s.io/cloud-provider-openstack/pkg/cloudprovider/providers/openstack"
+	md "k8s.io/cloud-provider-openstack/pkg/util/metadata"
```
Comment (lingxiankong) [inline pkg/csi/cinder/openstack/openstack.go]: why not just use `metadata` as package name?

File: pkg/csi/cinder/openstack/openstack_instances.go [hunk 7]
```diff
@@ -2,6 +2,7 @@ package openstack
 
 import (
 	"github.com/gophercloud/gophercloud/openstack/compute/v2/servers"
+	openstack_provider "k8s.io/cloud-provider-openstack/pkg/cloudprovider/providers/openstack"
```
Comment (lingxiankong) [inline pkg/csi/cinder/openstack/openstack_instances.go]: Package name should be in lower case, with no under_scores or mixedCaps, so `cpo` could be used as in other files.

File: pkg/csi/cinder/openstack/openstack_mock.go [hunk 8]
```diff
@@ -21,6 +21,7 @@ import (
 	"github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes"
 	"github.com/gophercloud/gophercloud/openstack/compute/v2/servers"
 	"github.com/stretchr/testify/mock"
+	openstack_provider "k8s.io/cloud-provider-openstack/pkg/cloudprovider/providers/openstack"
```
Comment (lingxiankong) [inline pkg/csi/cinder/openstack/openstack_mock.go]: Ditto

File: pkg/csi/cinder/sanity/fakecloud.go [hunk 9]
```diff
@@ -8,6 +8,7 @@ import (
 	"github.com/gophercloud/gophercloud/openstack/blockstorage/v3/snapshots"
 	"github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes"
 	"github.com/gophercloud/gophercloud/openstack/compute/v2/servers"
+	openstack_provider "k8s.io/cloud-provider-openstack/pkg/cloudprovider/providers/openstack"
```
Comment (lingxiankong) [inline pkg/csi/cinder/sanity/fakecloud.go]: Ditto

File: docs/using-cinder-csi-plugin.md [hunk 10]
```diff
@@ -41,6 +41,13 @@ Encode your ```$CLOUD_CONFIG``` file content using base64.
 Update ```cloud.conf``` configuration in ```manifests/cinder-csi-plugin/csi-secret-cinderplugin.yaml``` file
 by using the result of the above command.
 
+> NOTE: openstack supports get metadata data for new deployed vm through both config drive and metadata service methods. If you need modify the search order, please add Metadata section in your cloud.conf which is openstack cloud definition. For example, below sample makes CSI pod first search config drive then metadata service. If you don't provide the value, then default search order `configDrive, metadataService` will be used.
```
Comment (lingxiankong) [inline docs/using-cinder-csi-plugin.md]: Maybe you didn't see my previous suggestion, which I think is more clear and succinct

> NOTE: In OpenStack, the compute instance uses either config drive or metadata service to retrieve instance-specific data. As the cluster administrator, you are able to config the order in the cloud config file for cinder-csi-plugin, the default configuration is as follows:

File: pkg/csi/cinder/openstack/openstack.go (hunk 6 above)
Comment (lingxiankong) [reply pkg/csi/cinder/openstack/openstack.go]: Change missing?

Comment (jichenjc) [reply pkg/csi/cinder/openstack/openstack.go]: I think I added a comment ,why it's not showing? werid..

I can't do so because if I move to metadata, it will be duplicate to openstack_metadata.go
the unit will fail

File: go.mod [hunk 11]
```diff
@@ -9,6 +9,7 @@ require (
 	github.com/coreos/go-systemd v0.0.0-20190620071333-e64a0ec8b42a // indirect
 	github.com/emicklei/go-restful v2.9.6+incompatible // indirect
 	github.com/evanphx/json-patch v4.5.0+incompatible // indirect
+	github.com/go-logfmt/logfmt v0.4.0 // indirect
```
Comment (chrigl) [inline go.mod]: Could you try to run `go mod tidy`? No idea where this comes from, because you didn't change any dependencies.

Everything else lgtm.

Comment (jichenjc) [reply go.mod]: done, thanks

**Comment by ramineni** [comment]
Thanks.
/lgtm

**Comment by lingxiankong** [comment]
/lgtm
/approve

Thanks, @jichenjc
