### PR TITLE
[cinder-csi-plugin] Fix filesystem resize

### LINKED ISSUE #1436: [cinder-csi-plugin] Filesystem size stays the same after PVC resize
/kind bug

**What happened**:
When I try to resize a PVC as it says in the [example](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/cinder-csi-plugin/examples.md#volume-expansion-example) the filesystem size stays the same.

```sh
❯ oc get pvc
NAME           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
cinder-claim   Bound    pvc-98d9a874-27cf-4542-bbaa-6298ef282dd3   1Gi        RWO            standard-csi   25s
❯ oc exec example -- df -h /usr/share/nginx/html
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdb        976M  2.6M  958M   1% /usr/share/nginx/html
❯ oc edit pvc cinder-claim
persistentvolumeclaim/cinder-claim edited
❯ oc get pvc
NAME           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
cinder-claim   Bound    pvc-98d9a874-27cf-4542-bbaa-6298ef282dd3   2Gi        RWO            standard-csi   81s
❯ oc exec example -- df -h /usr/share/nginx/html
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdb        976M  2.6M  958M   1% /usr/share/nginx/html
```

List of events doesn't show any errors:

```sh
❯ oc describe pvc
Name:          cinder-claim
Namespace:     default
StorageClass:  standard-csi
Status:        Bound
Volume:        pvc-98d9a874-27cf-4542-bbaa-6298ef282dd3
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: cinder.csi.openstack.org
               volume.kubernetes.io/selected-node: mfedosin-rgrmg-worker-0-xwwvv
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      2Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Mounted By:    example
Events:
  Type     Reason                      Age   From                                                                                   Message
  ----     ------                      ----  ----                                                                                   -------
  Normal   WaitForFirstConsumer        100s  persistentvolume-controller                                                            waiting for first consumer to be created before binding
  Normal   Provisioning                90s   cinder.csi.openstack.org_mfedosin-rgrmg-master-1_bd43f952-680f-4245-a2fb-bf0a5fbff738  External provisioner is provisioning volume for claim "default/cinder-claim"
  Normal   ExternalProvisioning        90s   persistentvolume-controller                                                            waiting for a volume to be created, either by external provisioner "cinder.csi.openstack.org" or manually created by system administrator
  Normal   ProvisioningSucceeded       89s   cinder.csi.openstack.org_mfedosin-rgrmg-master-1_bd43f952-680f-4245-a2fb-bf0a5fbff738  Successfully provisioned volume pvc-98d9a874-27cf-4542-bbaa-6298ef282dd3
  Warning  ExternalExpanding           22s   volume_expand                                                                          Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.
  Normal   Resizing                    22s   external-resizer cinder.csi.openstack.org                                              External resizer is resizing volume pvc-98d9a874-27cf-4542-bbaa-6298ef282dd3
  Normal   FileSystemResizeRequired    22s   external-resizer cinder.csi.openstack.org                                              Require file system resize of volume on node
  Normal   FileSystemResizeSuccessful  20s   kubelet, mfedosin-rgrmg-worker-0-xwwvv                                                 MountVolume.NodeExpandVolume succeeded for volume "pvc-98d9a874-27cf-4542-bbaa-6298ef282dd3"
```

**What you expected to happen**:

Filesystem size should be 2Gi

**How to reproduce it**:

Repeat steps from the [example](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/cinder-csi-plugin/examples.md#volume-expansion-example). On the last one (where the filesystem size should be increased) nothing happens.

**Anything else we need to know?**:
I use ext4 fs for the volume

### PR DESCRIPTION
**Pull request by Fedosin**
Now we use "findmnt" command to find the device path. Unfortunately, this command may return multiple entries of the same mount, but in fact we need just the first one.  To prevent this issue we add "--first-only" flag to the command.

Fixes #1436 

```release-note
[cinder-csi-plugin] Fixed the issue where the file system size stays the same when expanding the volume.
```

### CODE REVIEW

File: pkg/csi/cinder/nodeserver.go [hunk 1]
```diff
@@ -523,7 +523,16 @@ func (ns *nodeServer) NodeExpandVolume(ctx context.Context, req *csi.NodeExpandV
...
+
+	// Get volume path
+	// With Kubernetes version>=v1.19.0, expand request carries volume_path and
+	// staging_target_path, what csi requires is staging_target_path.
+	volumePath := req.GetStagingTargetPath()
+	if volumePath == "" {
+		// If Kubernetes version < v1.19.0 the volume_path would be
+		// having the staging_target_path information
+		volumePath = req.GetVolumePath()
+	}
```
Comment (ramineni) [inline pkg/csi/cinder/nodeserver.go:535]: @Fedosin could you explain your issue in more detail . 
NodeExpandVolume can be called after nodePublish , in that case,  in that case we cant use staging_target_path, volumepath stores the right value. please check here: https://github.com/gnufied/kubernetes/blob/master/pkg/volume/csi/csi_client.go#L101

It would be more helpful if you could log the issue with details  and the values you are receiving in volumePath and staging_target_path

**Comment by Fedosin** [comment]
@ramineni something like this:

I0824 09:24:45.735515 507082 utils.go:159] ID: 66 Req-ID: 0001-0011-openshift-storage-0000000000000001-cce6ebe3-e5ea-11ea-a920-0a580a810229 GRPC call: /csi.v1.Node/NodeExpandVolume
I0824 09:24:45.737321 507082 utils.go:160] ID: 66 Req-ID: 0001-0011-openshift-storage-0000000000000001-cce6ebe3-e5ea-11ea-a920-0a580a810229 GRPC request: {"capacity_range":{"required_bytes":2147483648},"staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-3c6426fa-7476-478f-b685-f8b7831ce70b/globalmount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}},"volume_id":"0001-0011-openshift-storage-0000000000000001-cce6ebe3-e5ea-11ea-a920-0a580a810229","volume_path":"/var/lib/kubelet/pods/43de2997-5f4e-4fb3-a0e4-7e0d303c6c37/volumes/kubernetes.io~csi/pvc-3c6426fa-7476-478f-b685-f8b7831ce70b/mount"}

Because of this, expansion is a no-op as getDevidePath() is not able to find the device path based on volume_path.

**Comment by gnufied** [comment]
shouldn't `/var/lib/kubelet/pods/43de2997-5f4e-4fb3-a0e4-7e0d303c6c37/volumes/kubernetes.io~csi/pvc-3c6426fa-7476-478f-b685-f8b7831ce70b/mount` be a bind mount of staging path?

**Comment by gnufied** [comment]
@Fedosin can you add release notes please?

**Comment by Fedosin** [comment]
@gnufied as I know release notes are for public facing features. and this is just a bugfix, so I think `fixes #1436` is enough.

**Comment by gnufied** [comment]
I am not sure how release notes are prepared for openstack cloudprovider but in rest of kubernetes repository, we do capture important bugs in release notes.

**Comment by jichenjc** [comment]
I am +1 to list bug fixes in release notes as this seems best practices in other k8s ecosystem repo...

**Comment by Fedosin** [comment]
@jichenjc @gnufied the release note has been added

**Comment by jichenjc** [comment]
/approve

thanks

**Comment by lingxiankong** [comment]
@ramineni Is this a candidate for backport?

**Comment by ramineni** [comment]
> @ramineni Is this a candidate for backport?

@lingxiankong right. I'll propose a PR for backport to 1.20
