### PR TITLE
[cinder-csi-plugin] Ephemeral volumes: wait for volume status to be available

### LINKED ISSUE #1403: csi-cinder-plugin ephemeral volume is not attached
[cinder-csi-plugin] Volume status must be available to reserve, but the status is creating
/kind bug

**What happened**:
When using ephemeral volumes, the following error is logged:

Warning  FailedMount  6s (x2 over 2m8s)  kubelet, ds-kube-minion-2  (combined from similar events): MountVolume.SetUp failed for volume "tmp" : rpc error: code = Internal desc = Ephermal Volume Attach: Failed to Attach Volume: failed to attach 83a34327-0c7b-4b19-b770-e267e57b335b volume to 8e185cfe-a865-410d-bb1f-8888711de794 compute: Bad request with: [POST https://openstack.lat.corp-apps.com:8774/v2.1/servers/8e185cfe-a865-410d-bb1f-8888711de794/os-volume_attachments], error message: {"badRequest": {"message": "Invalid input received: Invalid volume: Volume status must be available to reserve, but the status is creating. (HTTP 400) (Request-ID: req-0b03bd41-116e-4f9c-9d84-0909b59dbe7a)", "code": 400}}

It seems that the plugin does not wait for the volume to become available, fails and goes to create it over and over again, so after few minutes I had about a dozen of available ephemeral volumes in openstack but none of them gets attached to the pod.

**What you expected to happen**:

Wait for the volume status to become available.

**How to reproduce it**:

create a pod similar to https://github.com/kubernetes/cloud-provider-openstack/blob/master/examples/cinder-csi-plugin/inline/inline-example.yaml 

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: latest
- OpenStack version: Pike
- Others: k8s 1.18

### PR DESCRIPTION
**Pull request by ramineni**
**What this PR does / why we need it**:
**Which issue this PR fixes(if applicable)**:
fixes #1403 

**Special notes for reviewers**:

**Release note**:

```release-note
[cinder-csi-plugin] Fixed the issue that the ephemeral inline volume is yet available when attaching to the node.
```

### CODE REVIEW

File: pkg/csi/cinder/openstack/openstack_volumes.go [hunk 1]
```diff
@@ -222,6 +223,35 @@ func (os *OpenStack) WaitDiskAttached(instanceID string, volumeID string) error
 	return err
 }
 
+//WaitVolumeStatusAvailable waits for volume to be 'available'
```
Comment (eharney) [inline pkg/csi/cinder/openstack/openstack_volumes.go:226]: This code looks good, but it may be worth changing the comment to indicate that this only works for volumes moving directly from the "creating" state to the "available" state.

(This is always true for how WaitVolumeStatusAvailable is used here, but it may not be true for someone using it in a different context later.)

File: tests/sanity/cinder/fakecloud.go [hunk 2]
```diff
@@ -120,6 +120,11 @@ func (cloud *cloud) WaitDiskDetached(instanceID string, volumeID string) error {
 
 }
 
+func (cloud *cloud) WaitVolumeStatusAvailable(volumeID string) error {
+	return nil
+
```
Comment (jichenjc) [inline tests/sanity/cinder/fakecloud.go:125]: nit: 125 unnecessary

**Comment by jichenjc** [comment]
looks like our CI need bump version

```
2021-03-05 09:42:21.960946 | ubuntu-focal-citynetwork | Detected go version: go version go1.15 linux/amd64.
2021-03-05 09:42:21.960957 | ubuntu-focal-citynetwork | Kubernetes requires go1.16.0 or greater.
2021-03-05 09:42:21.960983 | ubuntu-focal-citynetwork | Please install go1.16.0 or later.
```

File: pkg/csi/cinder/openstack/openstack_volumes.go (hunk 1 above)
Comment (ramineni) [reply pkg/csi/cinder/openstack/openstack_volumes.go:226]: +1, Ill update

**Comment by ramineni** [comment]
> looks like our CI need bump version
> [theopenlab/openlab-zuul-jobs#1130](https://github.com/theopenlab/openlab-zuul-jobs/pull/1130)
> 
> ```
> 2021-03-05 09:42:21.960946 | ubuntu-focal-citynetwork | Detected go version: go version go1.15 linux/amd64.
> 2021-03-05 09:42:21.960957 | ubuntu-focal-citynetwork | Kubernetes requires go1.16.0 or greater.
> 2021-03-05 09:42:21.960983 | ubuntu-focal-citynetwork | Please install go1.16.0 or later.
> ```

@jichenjc right, its already take care in https://github.com/theopenlab/openlab-zuul-jobs/pull/1129 , but looks like it needs zuul restart

**Comment by jichenjc** [comment]
> > looks like our CI need bump version
> > [theopenlab/openlab-zuul-jobs#1130](https://github.com/theopenlab/openlab-zuul-jobs/pull/1130)
> > ```
> > 2021-03-05 09:42:21.960946 | ubuntu-focal-citynetwork | Detected go version: go version go1.15 linux/amd64.
> > 2021-03-05 09:42:21.960957 | ubuntu-focal-citynetwork | Kubernetes requires go1.16.0 or greater.
> > 2021-03-05 09:42:21.960983 | ubuntu-focal-citynetwork | Please install go1.16.0 or later.
> > ```
> 
> @jichenjc right, its already take care in [theopenlab/openlab-zuul-jobs#1129](https://github.com/theopenlab/openlab-zuul-jobs/pull/1129) , but looks like it needs zuul restart

ok, need ping openlab...

**Comment by ramineni** [comment]
@lingxiankong @jichenjc PTAL
