### PR TITLE
CCM: set predictable and proper server IP addresses order

### LINKED ISSUE #863: CCM: Incorrect network interfaces order, when multiple interfaces are used
/kind bug

**What happened**:

When k8s compute nodes have multiple network interfaces, CCM constantly change them:

```sh
$ kubectl get nodes -o wide
NAME       STATUS   ROLES    AGE   VERSION   INTERNAL-IP   EXTERNAL-IP     OS-IMAGE                                      KERNEL-VERSION               CONTAINER-RUNTIME
node0012   Ready    <none>   18d   v1.16.3   10.128.0.34   192.1.106.99    Red Hat Enterprise Linux Server 7.7 (Maipo)   3.10.0-1062.1.2.el7.x86_64   docker://18.9.7
node0013   Ready    <none>   18d   v1.16.3   10.1.0.10     192.1.106.76    Red Hat Enterprise Linux Server 7.7 (Maipo)   3.10.0-1062.1.2.el7.x86_64   docker://18.9.7
$ sleep 5m
$ kubectl get nodes -o wide
NAME       STATUS   ROLES    AGE   VERSION   INTERNAL-IP   EXTERNAL-IP     OS-IMAGE                                      KERNEL-VERSION               CONTAINER-RUNTIME
node0012   Ready    <none>   18d   v1.16.3   10.1.0.34     192.1.106.99    Red Hat Enterprise Linux Server 7.7 (Maipo)   3.10.0-1062.1.2.el7.x86_64   docker://18.9.7
node0013   Ready    <none>   18d   v1.16.3   10.1.0.10     192.1.106.76    Red Hat Enterprise Linux Server 7.7 (Maipo)   3.10.0-1062.1.2.el7.x86_64   docker://18.9.7
```

This behavior causes issues, when kube-apiserver tries to connect to kubelet for `logs` or `exec` command, when `10.128.0.0/24` subnet is not available for kube-apiserver

And loadbalancer pool members change every sync loop:

```
I1203 19:28:31.845065       1 openstack_loadbalancer.go:1130] Ensured pool 0027f480-d407-44f3-bb5d-7d7c95fcbe2d has member for node0013 at 10.1.0.34
I1203 19:28:31.845271       1 openstack_loadbalancer.go:1135] Deleting obsolete member adfed073-bade-46cf-8b16-3bdfed2c7a62 for pool 0027f480-d407-44f3-bb5d-7d7c95fcbe2d address 10.128.0.34
```

**What you expected to happen**:

I expect to see the first interface IP address for all nodes, or at least don't change the IP address orders on every reconciliation loop.

**How to reproduce it (as minimally and precisely as possible)**:

Create VMs with more than one network interfaces.

**Anything else we need to know?**:

https://github.com/golang/go/issues/27179 golang issue.

Even setting the `alpha.kubernetes.io/provided-node-ip` node annotation or specifying the `--node-ip` kubelet parameter doesn't solve the issue.

<details>
<summary>one liner to get the first interface private ip address on the node</summary>
  ip -o -4 addr show dev $(find /sys/class/net -type l -not -lname '*virtual*' -printf '%f\n' -quit) | cut -d ' ' -f 7 | cut -f 1 -d '/'
</details>

Just for the history, bugs with slightly similar symptoms:
* https://github.com/digitalocean/digitalocean-cloud-controller-manager/issues/126
* https://github.com/kubernetes/kubernetes/issues/61921

**Environment**:
- openstack-cloud-controller-manager version: 1.16
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

refs:
* https://github.com/kubernetes/kubernetes/issues/84490

### PR DESCRIPTION
**Pull request by kayrus**
**The binaries affected**:

- [x] openstack-cloud-controller-manager
- [ ] cinder-csi-plugin
- [ ] k8s-keystone-auth
- [ ] client-keystone-auth
- [ ] octavia-ingress-controller
- [ ] manila-csi-plugin
- [ ] manila-provisioner
- [ ] magnum-auto-healer
- [ ] barbican-kms-plugin

**What this PR does / why we need it**:

This PR sets predictable server IP addresses order:
1) interfaces private IPs
2) access IPs
3) metadata hostname
4) server object Addresses

**Which issue this PR fixes**:
fixes #863

**Release note**:

```release-note
CCM: set predictable and proper server IP addresses order
```

### CODE REVIEW

File: pkg/cloudprovider/providers/openstack/openstack.go [hunk 1]
```diff
@@ -671,9 +671,58 @@ func getServerByName(client *gophercloud.ServiceClient, name types.NodeName) (*S
...
+// * metadata hostname
+// * server object Addresses
+func nodeAddresses(srv *servers.Server, interfaces []attachinterfaces.Interface, networkingOpts NetworkingOpts) ([]v1.NodeAddress, error) {
 	addrs := []v1.NodeAddress{}
 
+	// parse private IP addresses first in an ordered manner
+	for _, iface := range interfaces {
+		for _, fixedIP := range iface.FixedIPs {
+			isIPv6 := net.ParseIP(fixedIP.IPAddress).To4() == nil
+			if !(isIPv6 && networkingOpts.IPv6SupportDisabled) {
```
Comment (lingxiankong) [inline pkg/cloudprovider/providers/openstack/openstack.go]: We don't need to check IPv6 here and L707, `getAddressByName` has a argument `needIPv6` for that.

File: pkg/cloudprovider/providers/openstack/openstack.go [hunk 2]
```diff
@@ -671,9 +671,58 @@ func getServerByName(client *gophercloud.ServiceClient, name types.NodeName) (*S
...
+// * interfaces private IPs
+// * access IPs
+// * metadata hostname
+// * server object Addresses
+func nodeAddresses(srv *servers.Server, interfaces []attachinterfaces.Interface, networkingOpts NetworkingOpts) ([]v1.NodeAddress, error) {
 	addrs := []v1.NodeAddress{}
 
+	// parse private IP addresses first in an ordered manner
+	for _, iface := range interfaces {
+		for _, fixedIP := range iface.FixedIPs {
```
Comment (lingxiankong) [inline pkg/cloudprovider/providers/openstack/openstack.go]: I think we only care about the nic with property `"port_state": "ACTIVE"`

File: pkg/cloudprovider/providers/openstack/openstack.go [hunk 3]
```diff
@@ -671,9 +671,58 @@ func getServerByName(client *gophercloud.ServiceClient, name types.NodeName) (*S
 	return &serverList[0], nil
 }
 
-func nodeAddresses(srv *servers.Server, networkingOpts NetworkingOpts) ([]v1.NodeAddress, error) {
+// IP addresses order:
+// * interfaces private IPs
+// * access IPs
+// * metadata hostname
+// * server object Addresses
```
Comment (lingxiankong) [inline pkg/cloudprovider/providers/openstack/openstack.go]: This should be `server object Addresses(floating type)` to be more specific

File: pkg/cloudprovider/providers/openstack/openstack.go (hunk 2 above)
Comment (kayrus) [reply pkg/cloudprovider/providers/openstack/openstack.go]: added an extra check

File: pkg/cloudprovider/providers/openstack/openstack.go (hunk 3 above)
Comment (kayrus) [reply pkg/cloudprovider/providers/openstack/openstack.go]: added

File: pkg/cloudprovider/providers/openstack/openstack.go (hunk 1 above)
Comment (kayrus) [reply pkg/cloudprovider/providers/openstack/openstack.go]: Though `getAddressByName` func has this option, the `nodeAddresses` func can be called from other places.

**Comment by kayrus** [comment]
@lingxiankong kindly ping

**Comment by kayrus** [comment]
@lingxiankong kindly ping

**Comment by lingxiankong** [comment]
Hi @kayrus, sorry for the delay, i was distracted by some internal stuff these days, will try to come back for review tomorrow.

**Comment by lingxiankong** [comment]
Thanks for this fix!

/lgtm
/approve
