### PR TITLE
[manila-csi-plugin] ControllerExpandVolume rounds up size to GiB

### LINKED ISSUE #1764: [manila-csi-plugin] expanding volume stuck with "Invalid input received: New size for extend must be greater than current size."
/kind bug

**What happened**:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: cephfs.manila.csi.openstack.org
  creationTimestamp: "2021-11-16T23:21:08Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: pv-claim-admin-eguide
  namespace: admin-eguide
  resourceVersion: "647884816"
  uid: b3fefda5-eef7-4ef3-9cb8-4cb38c1fb9d2
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4G
  storageClassName: cephfs-no-backup
  volumeMode: Filesystem
  volumeName: pvc-b3fefda5-eef7-4ef3-9cb8-4cb38c1fb9d2
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 3Gi
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-01-18T18:27:24Z"
    status: "True"
    type: Resizing
  phase: Bound
```

Logs:
```
I0118 18:22:18.681066       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"admin-eguide", Name:"pv-claim-admin-eguide", UID:"b3fefda5-eef7-4ef3-9cb8-4cb38c1fb9d2", APIVersion:"v1", ResourceVersion:"647870433", FieldPath:""}): type: 'Normal' reason: 'Resizing' External resizer is resizing volume pvc-b3fefda5-eef7-4ef3-9cb8-4cb38c1fb9d2
I0118 18:22:20.611858       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"admin-eguide", Name:"pv-claim-admin-eguide", UID:"b3fefda5-eef7-4ef3-9cb8-4cb38c1fb9d2", APIVersion:"v1", ResourceVersion:"647870433", FieldPath:""}): type: 'Warning' reason: 'VolumeResizeFailed' resize volume "pvc-b3fefda5-eef7-4ef3-9cb8-4cb38c1fb9d2" by resizer "cephfs.manila.csi.openstack.org" failed: rpc error: code = Unknown desc = Bad request with: [POST https://openstack.cern.ch:8786/v2/8b4848c0-1d92-4184-8715-3ccab5f4634a/shares/6c126f2d-f04c-41a1-bb36-3a7740ff1b83/action], error message: {"badRequest": {"code": 400, "message": "Invalid input received: New size for extend must be greater than current size. (current: 3, extended: 3)."}}
```

**What you expected to happen**:

The request should have succeeded.

**How to reproduce it**:

Expand a volume to a value that's not aligned to GiB.

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: manila-csi-plugin v1.22.0
- OpenStack version:
- Others:

### PR DESCRIPTION
**Pull request by gman0**
**What this PR does / why we need it**:

`ControllerExpandVolume` doesn't round up new size to GiB leading to an error described in #1764. This PR fixes `bytesToGiB` which `ControllerExpandVolume` uses to convert the input size in bytes to GiB.

**Which issue this PR fixes(if applicable)**:
fixes #1764 

**Special notes for reviewers**:

Logs:
```
I0124 13:50:37.660046       1 driver.go:314] [ID:15] GRPC call: /csi.v1.Controller/ControllerExpandVolume
I0124 13:50:37.660069       1 driver.go:315] [ID:15] GRPC request: {"capacity_range":{"required_bytes":2000000000},"secrets":"***stripped***","volume_capability":{"AccessType":{"Mount":{}},"access_mode":{"mode":5}},"volume_id":"b9eeed27-a1f8-4de2-8161-9af786ba24b8"}
I0124 13:50:37.660393       1 client.go:252] Using user-agent manila-csi-plugin/f1499fbb-dirty gophercloud/2.0.0
I0124 13:50:40.961397       1 driver.go:320] [ID:15] GRPC response: {"capacity_bytes":2147483648}
I0124 14:04:45.315667       1 driver.go:314] [ID:16] GRPC call: /csi.v1.Controller/ControllerGetCapabilities
I0124 14:04:45.315761       1 driver.go:315] [ID:16] GRPC request: {}
I0124 14:04:45.316042       1 driver.go:320] [ID:16] GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":5}}},{"Type":{"Rpc":{"type":9}}}]}
I0124 14:04:45.318129       1 driver.go:314] [ID:17] GRPC call: /csi.v1.Controller/ControllerExpandVolume
I0124 14:04:45.318151       1 driver.go:315] [ID:17] GRPC request: {"capacity_range":{"required_bytes":3221225472},"secrets":"***stripped***","volume_capability":{"AccessType":{"Mount":{}},"access_mode":{"mode":5}},"volume_id":"b9eeed27-a1f8-4de2-8161-9af786ba24b8"}
I0124 14:04:45.318986       1 client.go:252] Using user-agent manila-csi-plugin/f1499fbb-dirty gophercloud/2.0.0
I0124 14:04:49.177117       1 driver.go:320] [ID:17] GRPC response: {"capacity_bytes":3221225472}
```

Issue in the linked bug report now goes away and resizing works correctly despite requesting new size in wrong units.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by gman0** [comment]
Another approach would be to return an error on values that are not aligned to GiB, but to stay consistent with what `CreateVolume` does, it's probably better to just silently round up.

**Comment by gman0** [comment]
PTAL @ramineni @gouthampacha @tombarron

File: pkg/csi/manila/controllerserver.go [hunk 1]
```diff
@@ -452,24 +452,23 @@ func (cs *controllerServer) ControllerExpandVolume(ctx context.Context, req *csi
 
 	// Try to expand the share
 
-	currentSizeInBytes := int64(share.Size * bytesInGiB)
+	desiredSizeInGiB := bytesToGiB(req.GetCapacityRange().GetRequiredBytes())
 
-	if currentSizeInBytes >= req.GetCapacityRange().GetRequiredBytes() {
+	if share.Size >= desiredSizeInGiB {
```
Comment (ramineni) [inline pkg/csi/manila/controllerserver.go:457]: @gman0 trying to understand here , isnt it the same . before you are comparing the size in bytes , now in GB . Is minimum supported size is 1Gi?

Comment (gman0) [reply pkg/csi/manila/controllerserver.go:457]: @ramineni this is actually what causes the bug described in #1764. Here it is comparing values in bytes without first rounding them to GiB. We first need to convert them to GiB and only then check whether the resize should proceed or not.

Without this PR, `req.GetCapacityRange().GetRequiredBytes()` ends up being round down to the closest GiB value. If users use GB units instead of GiB, and the converted values differ only by 1, then `roundDownToGiB(req.GetCapacityRange().GetRequiredBytes()) == currentSizeInGiB`.

**Comment by ramineni** [comment]
@gman0 looks good to me. Hope its documented somewhere that it gets round up GiB , when the unit given is GB

**Comment by gman0** [comment]
@ramineni it's not documented actually. The allocation unit in Manila is GiB, so it is implied that that's what users are going to get in any case. But it certainly wouldn't hurt to put this in the docs, that's for sure.

I hope that's a correct assumption @gouthampacha ^ ?

**Comment by gouthampacha** [comment]
> @ramineni it's not documented actually. The allocation unit in Manila is GiB, so it is implied that that's what users are going to get in any case. But it certainly wouldn't hurt to put this in the docs, that's for sure.
> 
> I hope that's a correct assumption @gouthampacha ^ ?

Yes; and this is true across OpenStack storage -- the unit of measurement is gibibytes (GiB) and minimum size of volumes (cinder) and shares (manila) is 1 GiB -- the API will reject fractional size requests, so it makes sense for the CSI drivers to convert and round up when the request isn't in whole GiB numbers. +1 on adding this to the manila/cinder-csi docs as well.

Thank you @gman0 

/lgtm
/approve
